spring.application.name=main

# Datasource
spring.datasource.url=jdbc:sqlite:mydb.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

# Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate

# Flyway
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
